#!/bin/sh

## Monitor setting
# if [[ $(xrandr --listmonitors | wc -l) > 2 ]]; then
#     bspc monitor eDP-1  -d 0 2 3 4 5 6 7 8 9
#     bspc monitor HDMI-2 -d 1
#     bspc desktop -f "^2"
# else
#     bspc monitor -d 1 2 3 4 5 6 7 8 9
# fi

bspc monitor -d 1 2 3 4 5 6 7 8 9

## Bspwm Config
bspc config automatic_scheme longest_side
bspc config border_width 2
bspc config -m primary top_padding 40
bspc config window_gap 10
bspc config focus_follows_pointer false
bspc config focused_border_color "#ff5555"
bspc config single_monocle true
bspc config borderless_monocle false

## Bspwm Rules
bspc rule -a Emacs state=tiled
bspc rule -a "Image Lounge" state=floating center=on
bspc rule -a "Emacs:SIMPLEMPC" state=floating center=on rectangle="1080x720+0+0"
bspc rule -a GoldenDict state=floating rectangle="400x500+1500+40"

## Exec Once
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill --no-fehbg ~/Pictures/wallpaper/v2-3ff3d6a85edb2f19d343668d24ed9269_r.jpg
light-locker --no-late-locking --lock-on-suspend --lock-on-lid &
pgrep -f lxqt-policykit-agent > /dev/null || lxqt-policykit-agent > /dev/null &
dunst > /dev/null &
fcitx5 --replace -d > /dev/null
picom &
pgrep -x udiskie > /dev/null || udiskie -t &
~/.config/polybar/launch.sh 
pgrep -f jieba-server.py > /dev/null || ~/.pydev/bin/python ~/.emacs.d/elpa/jieba/jieba-server.py &
