#!/bin/bash
# https://github.com/elkowar/eww/issues/833#issuecomment-1660846460
bspc subscribe node_state | while read -r _ _ _ _ state flag; do
  if [ "$state" != "fullscreen" ]; then
    continue
  fi

  if [ "$flag" == on ]; then
    # eww close-all
    pkill picom
  else
    xrandr --output eDP1 --auto
    picom &
    # eww open bar
  fi
done &
