config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  impignore:
  - '*/__pycache__/*'
  - '*/rime/build/*'
  - '*/rime/dicts/*'
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_offlineimaprc:
    src: offlineimaprc
    dst: ~/.offlineimaprc
  f_btop.conf:
    src: config/btop/btop.conf
    dst: ~/.config/btop/btop.conf
  d_lsd:
    src: config/lsd
    dst: ~/.config/lsd
  f_mpd.conf:
    src: config/mpd/mpd.conf
    dst: ~/.config/mpd/mpd.conf
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_qutebrowser:
    src: config/qutebrowser
    dst: ~/.config/qutebrowser
  d_qtile:
    src: config/qtile
    dst: ~/.config/qtile
  d_st:
    src: st
    dst: ~/.st
  d_rime:
    src: local/share/fcitx5/rime
    dst: ~/.local/share/fcitx5/rime
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_autostart:
    src: config/autostart
    dst: ~/.config/autostart
profiles:
  bardust:
    dotfiles:
    - f_zshrc
    - f_offlineimaprc
    - f_btop.conf
    - d_lsd
    - f_mpd.conf
    - d_mpv
    - d_picom
    - f_starship.toml
    - d_qutebrowser
    - d_qtile
    - d_st
    - d_rime
    - d_rofi
    - d_autostart
