config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_offlineimaprc:
    src: offlineimaprc
    dst: ~/.offlineimaprc
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  f_btop.conf:
    src: config/btop/btop.conf
    dst: ~/.config/btop/btop.conf
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_eww:
    src: config/eww
    dst: ~/.config/eww
  d_lsd:
    src: config/lsd
    dst: ~/.config/lsd
  f_mpd.conf:
    src: config/mpd/mpd.conf
    dst: ~/.config/mpd/mpd.conf
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
profiles:
  mrdust:
    dotfiles:
    - f_zshrc
    - f_offlineimaprc
    - d_alacritty
    - d_bspwm
    - f_btop.conf
    - d_dunst
    - d_eww
    - d_lsd
    - f_mpd.conf
    - d_mpv
    - d_picom
    - d_polybar
    - f_starship.toml
