#!/bin/bash

if [[ $1 == "up" ]]; then
    brightnessctl set +5%
elif [[ $1 == "down" ]]; then
    brightnessctl set 5%-
else
    cur=$(brightnessctl get)
    max=$(brightnessctl max)
    echo $((100*cur/max))
    inotifywait -e modify -m /sys/class/backlight/intel_backlight/brightness -q|
        while read line
        do
            cur=$(brightnessctl get)
            max=$(brightnessctl max)
            echo $((100*cur/max))
        done
fi
