#!/bin/bash

mail_dir=~/Mail

function get_mail_num () {
    count=$(fd -p '/new/' $mail_dir | wc -l)
    echo $count
}

get_mail_num

inotifywait -e create,delete,modify,move -rmq --include 'new' $mail_dir |
    while read line
    do
        get_mail_num
    done
