#!/usr/bin/python
import orjson
import nmcli
import subprocess

def get_wifi_current():
    state = nmcli.device.show("wlan0")
    connected = state["GENERAL.CONNECTION"]
    return connected

def get_wifi_list():
    ret = []
    for each in nmcli.device.wifi():
        ret.append({"name": each.ssid, "signal": each.signal})
    return ret

if __name__ == "__main__":
    import sys
    arg = sys.argv[1]
    if arg == "gui":
        res = subprocess.check_output(["eww", "get", "net-gui-p"])
        exists_p = res.decode().strip() == "false"
        subprocess.run(["eww", "open" if exists_p else "close", "net"])
        subprocess.run(["eww", "update", "net-gui-p=%s" % ("true" if exists_p else "false")])
    elif arg == "state":
        nmcli.disable_use_sudo()
        nmcli.connection()
        lst = get_wifi_list()
        connected = get_wifi_current()
        if connected is None:
            connected == ""
        ret = {"connection": connected, "data": lst}
        print(orjson.dumps(ret).decode())
        
