#!/bin/bash

function volume_get_state () {
    temp=$(pulseaudio-ctl full-status)
    status=($temp)
    echo '{"mute":"'${status[1]}'","value":'${status[0]}'}'
}

volume_get_state
pactl subscribe |
    while read line
    do
        if [[ $line == *"on sink"* ]]; then
            volume_get_state
        fi
    done
