#!/bin/bash

info_to_icon() {    
    case $1 in
        'Sunny')
            echo '☀ ';;
        'Night Clear')
            echo ' ';;
        'Mostly Sunny')
            echo ' ';;
        'Partly Cloudy')
            echo ' ';;
        'Partly Cloudy Night')
            echo ' ';;
        'Mostly Cloudy')
            echo ' ';;
        'Mostly Cloudy Night')
            echo ' ';;
        'Cloudy')
            echo '󰖐 ';;
        'Scattered Showers')
            echo ' ';;
        'Rain')
            echo ' ';;
        'Foggy')
            echo ' ';;
        'Rain and Snow')
            echo '  ';;
        'Snow')
            echo ' ';;
        'Wind')
            echo ' ';;
        'Thunderstorms')
            echo ' ';;
        'Scattered')
            echo '';;
        *)
            echo "$1";;
        esac
}

Id="a2c7286fad9237782336c23aa5015896fa981ec352246533b0b55b1a90ede284"
data=$(python ~/scripts/weather_scraper.py -n 5 $Id)
city=$(echo $data | jq '.location.city' -r)
weather=$(echo $data | jq '.location.forecasts[0].weather[]')

dtime=($(echo $weather | jq '.time' -r))
info=($(echo $weather | jq '.info' -r))
temperature=($(echo $weather | jq '.temperature' -r))
rain_chance=($(echo $weather | jq '."rain chance"' -r))




echo "["
for i in {0..4}; do
    icon=$(info_to_icon ${info[$i]})
    tooltip="$city - ${dtime[$i]}\n  ${temperature[$i]}\n󰖗  ${rain_chance[$i]}"
    item="{\"icon\": \"$icon\", \"tooltip\": \"$tooltip\"}"
    echo "$item,"
done

echo "{}]"
