#!/bin/bash

function bspc-print () {
    focusDid=$(bspc wm -d | jq ".monitors[0].focusedDesktopId")
    focusName=$(bspc query -D --names -d ${focusDid})
    echo -n "["
    for i in $(seq 1 9);
    do
        if [[ $i == $focusName ]]; then
            echo -n "2"
        elif [[ -n $(bspc query -N -d ${i}) ]]; then
            echo -n "1"
        else
            echo -n "0"
        fi
        if [[ $i -ne "9" ]]; then
            echo -n ","
        fi
    done
    echo "]"
}
bspc-print
bspc subscribe node_focus desktop_focus |
    while read line
    do
        bspc-print
    done

